// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL68_MR3OKIo3XvLkMdw3qKgjAwR2H1eQ',
    appId: '1:670966149763:web:b65ba24c5f281a4e4a61b6',
    messagingSenderId: '670966149763',
    projectId: 'my-pro-fcc67',
    authDomain: 'my-pro-fcc67.firebaseapp.com',
    storageBucket: 'my-pro-fcc67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CAoOA912yva-D9-2TDAxztG4FPOpQ5Q',
    appId: '1:670966149763:android:9c62a31d842e37574a61b6',
    messagingSenderId: '670966149763',
    projectId: 'my-pro-fcc67',
    storageBucket: 'my-pro-fcc67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2JBymmDYrqbi-Wpq8ZGhe7XrYKqV1Azk',
    appId: '1:670966149763:ios:bc0a5be6952660f34a61b6',
    messagingSenderId: '670966149763',
    projectId: 'my-pro-fcc67',
    storageBucket: 'my-pro-fcc67.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2JBymmDYrqbi-Wpq8ZGhe7XrYKqV1Azk',
    appId: '1:670966149763:ios:bc0a5be6952660f34a61b6',
    messagingSenderId: '670966149763',
    projectId: 'my-pro-fcc67',
    storageBucket: 'my-pro-fcc67.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL68_MR3OKIo3XvLkMdw3qKgjAwR2H1eQ',
    appId: '1:670966149763:web:1afb287628c20f9f4a61b6',
    messagingSenderId: '670966149763',
    projectId: 'my-pro-fcc67',
    authDomain: 'my-pro-fcc67.firebaseapp.com',
    storageBucket: 'my-pro-fcc67.firebasestorage.app',
  );
}
